# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_dagmcdagmcmpimpichmpi_prefixmpi_mpichpython3.11.____cpython:
        CONFIG: linux_64_dagmcdagmcmpimpichmpi_prefixmpi_mpichpython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcdagmcmpimpichmpi_prefixmpi_mpichpython3.12.____cpython:
        CONFIG: linux_64_dagmcdagmcmpimpichmpi_prefixmpi_mpichpython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcdagmcmpimpichmpi_prefixmpi_mpichpython3.13.____cp313:
        CONFIG: linux_64_dagmcdagmcmpimpichmpi_prefixmpi_mpichpython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcdagmcmpinompimpi_prefixnompipython3.11.____cpython:
        CONFIG: linux_64_dagmcdagmcmpinompimpi_prefixnompipython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcdagmcmpinompimpi_prefixnompipython3.12.____cpython:
        CONFIG: linux_64_dagmcdagmcmpinompimpi_prefixnompipython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcdagmcmpinompimpi_prefixnompipython3.13.____cp313:
        CONFIG: linux_64_dagmcdagmcmpinompimpi_prefixnompipython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcdagmcmpiopenmpimpi_prefixmpi_openmpipython3.11.____cpython:
        CONFIG: linux_64_dagmcdagmcmpiopenmpimpi_prefixmpi_openmpipython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcdagmcmpiopenmpimpi_prefixmpi_openmpipython3.12.____cpython:
        CONFIG: linux_64_dagmcdagmcmpiopenmpimpi_prefixmpi_openmpipython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcdagmcmpiopenmpimpi_prefixmpi_openmpipython3.13.____cp313:
        CONFIG: linux_64_dagmcdagmcmpiopenmpimpi_prefixmpi_openmpipython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcnodagmcmpimpichmpi_prefixmpi_mpichpython3.11.____cpython:
        CONFIG: linux_64_dagmcnodagmcmpimpichmpi_prefixmpi_mpichpython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcnodagmcmpimpichmpi_prefixmpi_mpichpython3.12.____cpython:
        CONFIG: linux_64_dagmcnodagmcmpimpichmpi_prefixmpi_mpichpython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcnodagmcmpimpichmpi_prefixmpi_mpichpython3.13.____cp313:
        CONFIG: linux_64_dagmcnodagmcmpimpichmpi_prefixmpi_mpichpython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcnodagmcmpinompimpi_prefixnompipython3.11.____cpython:
        CONFIG: linux_64_dagmcnodagmcmpinompimpi_prefixnompipython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcnodagmcmpinompimpi_prefixnompipython3.12.____cpython:
        CONFIG: linux_64_dagmcnodagmcmpinompimpi_prefixnompipython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcnodagmcmpinompimpi_prefixnompipython3.13.____cp313:
        CONFIG: linux_64_dagmcnodagmcmpinompimpi_prefixnompipython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcnodagmcmpiopenmpimpi_prefixmpi_openmpipython3.11.____cpython:
        CONFIG: linux_64_dagmcnodagmcmpiopenmpimpi_prefixmpi_openmpipython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcnodagmcmpiopenmpimpi_prefixmpi_openmpipython3.12.____cpython:
        CONFIG: linux_64_dagmcnodagmcmpiopenmpimpi_prefixmpi_openmpipython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_dagmcnodagmcmpiopenmpimpi_prefixmpi_openmpipython3.13.____cp313:
        CONFIG: linux_64_dagmcnodagmcmpiopenmpimpi_prefixmpi_openmpipython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcdagmcmpimpichmpi_prefixmpi_mpichpython3.11.____cpython:
        CONFIG: linux_aarch64_dagmcdagmcmpimpichmpi_prefixmpi_mpichpython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcdagmcmpimpichmpi_prefixmpi_mpichpython3.12.____cpython:
        CONFIG: linux_aarch64_dagmcdagmcmpimpichmpi_prefixmpi_mpichpython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcdagmcmpimpichmpi_prefixmpi_mpichpython3.13.____cp313:
        CONFIG: linux_aarch64_dagmcdagmcmpimpichmpi_prefixmpi_mpichpython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcdagmcmpinompimpi_prefixnompipython3.11.____cpython:
        CONFIG: linux_aarch64_dagmcdagmcmpinompimpi_prefixnompipython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcdagmcmpinompimpi_prefixnompipython3.12.____cpython:
        CONFIG: linux_aarch64_dagmcdagmcmpinompimpi_prefixnompipython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcdagmcmpinompimpi_prefixnompipython3.13.____cp313:
        CONFIG: linux_aarch64_dagmcdagmcmpinompimpi_prefixnompipython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcdagmcmpiopenmpimpi_prefixmpi_openmpipython3.11.____cpython:
        CONFIG: linux_aarch64_dagmcdagmcmpiopenmpimpi_prefixmpi_openmpipython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcdagmcmpiopenmpimpi_prefixmpi_openmpipython3.12.____cpython:
        CONFIG: linux_aarch64_dagmcdagmcmpiopenmpimpi_prefixmpi_openmpipython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcdagmcmpiopenmpimpi_prefixmpi_openmpipython3.13.____cp313:
        CONFIG: linux_aarch64_dagmcdagmcmpiopenmpimpi_prefixmpi_openmpipython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcnodagmcmpimpichmpi_prefixmpi_mpichpython3.11.____cpython:
        CONFIG: linux_aarch64_dagmcnodagmcmpimpichmpi_prefixmpi_mpichpython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcnodagmcmpimpichmpi_prefixmpi_mpichpython3.12.____cpython:
        CONFIG: linux_aarch64_dagmcnodagmcmpimpichmpi_prefixmpi_mpichpython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcnodagmcmpimpichmpi_prefixmpi_mpichpython3.13.____cp313:
        CONFIG: linux_aarch64_dagmcnodagmcmpimpichmpi_prefixmpi_mpichpython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcnodagmcmpinompimpi_prefixnompipython3.11.____cpython:
        CONFIG: linux_aarch64_dagmcnodagmcmpinompimpi_prefixnompipython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcnodagmcmpinompimpi_prefixnompipython3.12.____cpython:
        CONFIG: linux_aarch64_dagmcnodagmcmpinompimpi_prefixnompipython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcnodagmcmpinompimpi_prefixnompipython3.13.____cp313:
        CONFIG: linux_aarch64_dagmcnodagmcmpinompimpi_prefixnompipython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcnodagmcmpiopenmpimpi_prefixmpi_openmpipython3.11.____cpython:
        CONFIG: linux_aarch64_dagmcnodagmcmpiopenmpimpi_prefixmpi_openmpipython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcnodagmcmpiopenmpimpi_prefixmpi_openmpipython3.12.____cpython:
        CONFIG: linux_aarch64_dagmcnodagmcmpiopenmpimpi_prefixmpi_openmpipython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_dagmcnodagmcmpiopenmpimpi_prefixmpi_openmpipython3.13.____cp313:
        CONFIG: linux_aarch64_dagmcnodagmcmpiopenmpimpi_prefixmpi_openmpipython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
    maxParallel: 25
  timeoutInMinutes: 360
  variables: {}

  steps:
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
        export remote_url=$(Build.Repository.Uri)
        export sha=$(Build.SourceVersion)
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
